apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  spring.datasource.url: jdbc:mysql://my-rds-cluster-3.cluster-c72esgg00md4.us-east-1.rds.amazonaws.com/dbeks
  spring.datasource.username: master