apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  spring.datasource.url: jdbc:mysql://my-rds-cluster.cluster-czii0w8e65zv.ap-south-1.rds.amazonaws.com/dbeks
  spring.datasource.username: master