apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: public.ecr.aws/e8n4i2w8/frontend:latest
        ports:
        - containerPort: 8080
        securityContext:  
          privileged: false 
          allowPrivilegeEscalation: false       
          readOnlyRootFilesystem: true
          runAsUser: 1005  
          runAsNonRoot: true 
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-config
          mountPath: /etc/nginx/conf.d 
        resources:
          limits:
            memory: "500Mi"
            cpu: "1000m"
          requests:
            memory: "225Mi"
            cpu: "100m"
        # readinessProbe:
        #   httpGet:
        #     scheme: HTTP
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 5
        # livenessProbe:
        #   successThreshold: 1
        #   failureThreshold: 5
        #   periodSeconds: 15 
        #   initialDelaySeconds: 20
        #   timeoutSeconds: 5
        #   httpGet:
        #     path: /health
        #     port: 8080
        #     scheme: HTTP
      # nodeSelector:
      #   application: "frontend"
      # tolerations:
      # - key: "application"
      #   operator: "Equal"
      #   value: "frontend"
      #   effect: "NoSchedule"
    volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-config
        emptyDir: {}